# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivan Nikolov
email: mail@inikolov.info
description: > # this means to ignore newlines until "baseurl:"
  # TODO ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "inikolov89.github.io" # the base hostname & protocol for your site
twitter_username: inikolov89
github_username:  inikolov89
linkedin_username: ivan-nikolov-535a4988 
xing_username: Ivan_Nikolov17

# Build settings
markdown: kramdown
